"""random password is nullable

Revision ID: fc69656a159b
Revises: 87a3b6e6d629
Create Date: 2024-10-26 12:34:22.505897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc69656a159b'
down_revision: Union[str, None] = '87a3b6e6d629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'random_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'random_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
