---
services:
  payroll_db:
    image: postgres:12.16-alpine3.18
    container_name: payroll-db
    restart: unless-stopped
    ports:
      - 127.0.0.1:5434:5432
    env_file:
      - ../src/.env
    environment:
      PGDATA: /var/lib/postgresql/data/payroll/pgdata/
      POSTGRES_DB: payroll_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - apgdata:/var/lib/postgresql/data/payroll/pgdata/
    networks:
      - home


networks:
  home: {}
volumes:
  apgdata: {}
  redisstore: {}
  aminio_data: {}
  city-volume:
